import { z } from 'zod';

export const customerSchema = z.object({
  fullName: z.string().nullable().optional(),
  code: z.string().nullable().optional(),
  cardNumber: z.string().nullable().optional(),
  dob: z.string().nullable().optional(), 
  phone: z.string().nullable().optional(),
  zairyuAddress: z.string().nullable().optional(),
  zairyuRomajiAddress: z.string().nullable().optional(),
  postalCode: z.string().nullable().optional(),
  taxOfficeId: z.string().nullable().optional(),
  nenkinNumber: z.string().nullable().optional(),
  nenkinKatakanaName: z.string().nullable().optional(),
  bankAccounts: z.array(z.object({
    id: z.string().optional(),
    purpose: z.string(), // 'FIRST_REFUND' | 'SECOND_REFUND' | 'BOTH'
    bankCountry: z.string(), // 'JAPAN' | 'VIETNAM'
    bankPassbookUrls: z.array(z.string()).optional(),
    bankName: z.string().nullable().optional(),
    branchName: z.string().nullable().optional(),
    accountNumber: z.string().nullable().optional(),
    accountName: z.string().nullable().optional(),
    accountNameKatakana: z.string().nullable().optional(),
    swiftCode: z.string().nullable().optional(),
    bankBranchAddress: z.string().nullable().optional(),
    bankInstitutionCode: z.string().nullable().optional(),
    branchCode: z.string().nullable().optional(),
    bankAccountType: z.string().nullable().optional(),
  })).optional(),
  zairyuFrontUrl: z.string().nullable().optional(),
  zairyuBackUrl: z.string().nullable().optional(),
  passportUrl: z.string().nullable().optional(),
  departureStampUrl: z.string().nullable().optional(),
  nenkinBookUrl: z.string().nullable().optional(),
  nationality: z.string().nullable().optional(),
  sex: z.string().nullable().optional(),
  hasPermanentResidence: z.boolean().nullable().optional(),
  permanentResidenceDate: z.string().nullable().optional(),
  lastName: z.string().nullable().optional(),
  firstName: z.string().nullable().optional(),
  passportIssueDate: z.string().nullable().optional(),
  passportExpiryDate: z.string().nullable().optional(),
  placeOfBirth: z.string().nullable().optional(),
  overseasAddress: z.string().nullable().optional(),
  overseasCountry: z.string().nullable().optional(),
  myNumber: z.string().nullable().optional(),
  occupation: z.string().nullable().optional(),
  departureDate: z.string().nullable().optional(),
  headOfHouseholdName: z.string().nullable().optional(),
  relationshipToHead: z.string().nullable().optional(),
});

export type CustomerFormValues = z.infer<typeof customerSchema>;
